
- name: Base Playbook RHEL 8
  remote_user: ulsprovision
  hosts: all
  become: yes

  tasks:

# Add package wget
  - name: install wget
    yum:
      name: wget
      state: latest

# Install postfix
  - name: install postfix
    yum:
      name: postfix
      state: latest

# add rsync,git 
  - name: install rsync
    yum:
      name: rsync
      state: latest


  - name: install git
    yum:
      name: git
      state: latest

# Required for NetBackup Client.
  - name: install libnsl
    yum:
      name: libnsl
      state: latest

# add cronic

  - name: Add cronic script
    copy:
      src: resources/cronic/cronic
      dest: /usr/local/bin/cronic
      mode: u=rwx,g=rx,o=rx
      owner: root
      group: root


# selinux

  - name: install policycoreutils-python
    yum:
      name: policycoreutils-python-utils
      state: latest


  - name: install libselinux-python
    yum:
      name: libselinux-utils
      state: latest

  - name: set up email for root
    lineinfile:
       path: /etc/aliases
       state: present
       regexp: '^root:'
       line: 'root:           uls-linux-root@pitt.edu'

# remove motd - Red Hat Insights.
  - name: remove Red Hat Insights motd symlink
    file:
      path: /etc/motd.d/insights-client
      state: absent

# Setup Automatic Updates.
  - name: add yumcron email
    lineinfile:
      path: /etc/aliases
      line: "yumcron: mem375@pitt.edu,bdgregg@pitt.edu,ctgraham@pitt.edu"
      insertafter: EOF
      backup: yes
      state: present

  - name: run newaliases
    command: newaliases

  - name: Install dnf-automatic.
    yum:
      name: dnf-automatic
      state: latest

  - name: Copy automatic.conf to host.
    template:
      src: resources/dnf-automatic/automatic.conf
      dest: /etc/dnf/automatic.conf

  - name: Replace root with yumcron alias in /etc/dnf/automatic.conf
    replace:
      path: /etc/dnf/automatic.conf
      regexp: 'email_to = root'
      replace: 'email_to = yumcron'
      backup: yes

  - name: Replace root@example.com with uls-linux-root@pitt.edu in /etc/dnf/automatic.conf
    replace:
      path: /etc/dnf/automatic.conf
      regexp: 'email_from = root@example.com'
      replace: 'email_from = uls-linux-root@pitt.edu'
      backup: yes

  - name: start dnf-automatic-install
    service:
      name: dnf-automatic-install.timer
      state: started
      enabled: yes

