---
- import_playbook: set-hostname.yml
  tags:
        - build
- import_playbook: register-satellite.yml
  tags:
        - build
- import_playbook: install-base-software.yml
  tags:
        - build
- import_playbook: install-kerberos.yml
  tags:
        - build

